swagger: "2.0"
info:
  description: "This is API for [Ohjelmallien sisällönhallinta](https://ohsiha-webmc.herokuapp.com) project website."
  version: "0.0.2"
  title: "Markov chain blogpost website API."
  contact:
    email: "jussi.m.ristimaki@student.tut.fi"

# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths
basePath: /v1/
#
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /users:
    # binds a127 app logic to a route
    x-swagger-router-controller: users
    get:
      description: Lists all users on the website
      # used as the method name of the controller
      operationId: getUsers
      responses:
        200:
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/UserList"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /users/{userId}:
    # binds a127 app logic to a route
    x-swagger-router-controller: users
    get:
      description: Fetch information on a user based on ID.
      # used as the method name of the controller
      operationId: getUserById
      parameters:
        - in: path
          name: userId
          type: integer
          required: true
          description: ID of the user to retrieve.
      responses:
        200:
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/User"
        400:
          description: "Bad request. User ID must be an integer and bigger than 0."
          schema:
            $ref: '#/definitions/ErrorResponse'
        404:
          description: "A user with the specified ID was not found."
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /articles:
    x-swagger-router-controller: articles
    get:
      description: Retrieve articles.
      operationId: getArticles
      responses:
        200:
          description: Success
          schema:
            $ref: "#/definitions/Articles"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /articles/{articleId}:
    x-swagger-router-controller: articles
    get:
      description: Retrieve articles.
      operationId: getArticleById
      parameters:
        - in: path
          name: articleId
          type: integer
          required: true
          description: ID of the user to retrieve.
      responses:
        200:
          description: Success
          schema:
            $ref: "#/definitions/Article"
        400:
          description: "Bad request. Article ID must be an integer and bigger than 0."
          schema:
            $ref: '#/definitions/ErrorResponse'
        404:
          description: "An article with the specified ID was not found."
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /tweetdatalist:
    x-swagger-router-controller: tweetdata
    get:
      description: Retrieve list of tweet data container information.
      operationId: getTweetDataList
      responses:
        200:
          description: Success
          schema:
            $ref: "#/definitions/TweetDataList"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /tweetdatalist/{tweetDataId}:
    x-swagger-router-controller: tweetdata
    get:
      description: Retrieve information about tweet data with specified tweetDataId.
      operationId: getTweetDataById
      parameters:
        - in: path
          name: tweetDataId
          type: integer
          required: true
          description: ID of the tweet data container to retrieve.
      responses:
        200:
          description: Success
          schema:
            $ref: "#/definitions/TweetData"
        400:
          description: "Bad request. Tweet data ID must be an integer and bigger than 0."
          schema:
            $ref: '#/definitions/ErrorResponse'
        404:
          description: "Tweet data with the specified ID was not found."
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  UserList:
    type: "array"
    items:
      $ref: '#/definitions/UserElement'
  User:
    type: "object"
    properties:
      id:
        type: string
        description: Display user Id.
      name:
        type: string
        description: Name of user.
      tweetDataId:
        type: string
        description: Id of the tweet data container. Set to "null" if no data is found.
      articleIds:
        type: array
        items:
          type: integer
          description: List of articleIds created by the user. Empty list if not articles are found.
  UserElement:
    type: "object"
    properties:
      name:
        type: string
        description: Name of the user.
      userId:
        type: integer
        description: Id of the user.
  Articles:
    type: "array"
    items:
      $ref: '#/definitions/ArticleElement'
  ArticleElement:
    type: "object"
    properties:
      articleId:
        type: integer
        description: Id of the article.
      userId:
        type: integer
        description: Id of the author.
  Article:
    type: "object"
    properties:
      title:
        type: string
        description: Title of the article.
      articleId:
        type: integer
        description: Id of the article.
      content:
        type: string
        description: Content of the article.
      dateCreated:
        type: string
        description: Date of creation.
      userId:
        type: integer
        description: Id of the author.
      author:
        type: string
        description: Name of the author.
      comments:
        type: array
        items:
          type: string
          description: List of comments.
  TweetDataList:
    type: "array"
    items:
      type: "object"
      properties:
        tweetDataId:
          type: integer
          description: Id of the article.
        userId:
          type: integer
          description: Id of the user.
        author:
          type: string
          description: Name of the author.
  TweetData:
    type: "object"
    properties:
      tweetDataId:
        type: integer
        description: Id of the tweet data container.
      content:
        type: array
        items:
          type: string
          description: Content of the Data.
      dateCreated:
        type: string
        description: Date of creation.
      userId:
        type: integer
        description: Id of the author.
      author:
        type: string
        description: Name of the author.
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
        description: Error message.
