// app/models/user.js
// Javascript file for MongoDB User-schema intended for storing user information.

// Require 'mongoose' to get the needed schema object for user model.
var mongoose = require('mongoose');
var bcrypt   = require('bcrypt-nodejs');

// MongoDB schema for user model that is used for storing data to the MongoDB.
// !! Kokeile tehdä ES6 luokalla !!
var userSchema = mongoose.Schema({
  basicLocal: {
    email: String,
    password: String
  },
  googleAuth: {
    id: String,
    token: String,
    email: String,
    password: String
  }
});


// userSchema's methods.
userSchema.methods.genHash = function(password) {
  // Encrypts 'password' with salt generated by genSaltSync.
  return bcrypt.hashSync(password, bcrypt.genSaltSync(8), null);
};

userSchema.methods.validPassword = function(password) {
  // Compares given 'password' and hashed password in model.
  return bcrypt.compareSync(password, this.basicLocal.password);
}

module.exports = mongoose.model('User', userSchema);
